org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2-snapshot-2
loader_version=0.19.1
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0-mc26.2-snapshot-2
maven_group=tapm.swapcolumn

# Dependencies
fabric_api_version=0.145.5+26.2
